'use strict';
let state, department = 'all', view = 'today', toastTimer;
const modal = document.getElementById('modal');
const main = document.getElementById('main');
const navItems = [
  ['today','Сегодня','grid'],['people','Команда','people'],['access','Доступы','lock'],['expiries','Сроки действия','clock'],
  ['time','Контроль списаний','calendar'],['releases','Релизы','rocket'],['risks','Риски и блокеры','flag'],
  ['services','Данные и стенды','layers'],['grafana','Grafana','layers'],['knowledge','Знания','book'],['brief','Сводка управления','brief'],
  ['integrations','Источники и импорт','plug'],['research','Исследование','search']
];
const iconPaths = {
 grid:'M3 3h7v7H3zM14 3h7v7h-7zM3 14h7v7H3zM14 14h7v7h-7z', people:'M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2M9 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8M22 21v-2a4 4 0 0 0-3-3.87M16 3.13a4 4 0 0 1 0 7.75',
 lock:'M5 11h14v10H5zM8 11V7a4 4 0 0 1 8 0v4', clock:'M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18M12 7v5l3 2',
 calendar:'M3 5h18v16H3zM16 3v4M8 3v4M3 10h18M7 14h3M14 14h3M7 18h3', rocket:'M12 3l7 9-7 9-7-9zM12 3v18M5 12h14',
 flag:'M5 21V3M5 3h13l-3 5 3 5H5', layers:'M12 3l10 5-10 5L2 8zM2 13l10 5 10-5M2 18l10 5 10-5',
 book:'M12 5c-3-2-6-2-10-2v16c4 0 7 0 10 2 3-2 6-2 10-2V3c-4 0-7 0-10 2v16', brief:'M5 3h14v18H5zM8 7h8M8 11h8M8 15h5',
 plug:'M8 3v5M16 3v5M6 8h12v3a6 6 0 0 1-12 0zM12 17v5', search:'M10 3a7 7 0 1 0 0 14 7 7 0 0 0 0-14M15 15l6 6'
};
function icon(name){return `<svg class="nav-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${iconPaths[name]||iconPaths.grid}"/></svg>`;}
function e(value){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function rows(kind){return state.data[kind].filter(r=>department==='all'||r.departmentId===department);}
function person(id){return state.data.people.find(p=>p.id===id);}
function personName(id){return person(id)?.name||'Сотрудник не сопоставлен';}
function deptName(id){return state.departments.find(d=>d.id===id)?.short||id;}
function dateText(value){if(!value)return 'Дата не подтверждена';const d=new Date(value.length===10?value+'T12:00:00+03:00':value);return Number.isNaN(d.valueOf())?'Дата не подтверждена':d.toLocaleDateString('ru-RU',{timeZone:'Europe/Moscow',day:'numeric',month:'short',year:'numeric'});}
function daysUntil(date){return Math.round((Date.parse(date+'T00:00:00Z')-Date.parse(state.today+'T00:00:00Z'))/86400000);}
function source(row){const s=row.sourceRef;return `<small class="source">${e(s.system==='DEMO'?'Демонстрационные данные':s.system==='LOCAL'?'Локальная запись':s.system)} · ${e(s.objectId)}<br>${e(dateText(s.updatedAt))}${s.system!=='LOCAL'&&s.system!=='DEMO'?' · ручной импорт':''}</small>`;}
function editable(row){return ['LOCAL','DEMO'].includes(row.sourceRef.system);}
function tag(label,color=''){return `<span class="tag ${color}">${e(label)}</span>`;}
function toast(text){clearTimeout(toastTimer);const t=document.getElementById('toast');t.textContent=text;t.style.display='block';toastTimer=setTimeout(()=>{t.style.display='none';},4500);}
async function api(path,body,key){
 if(window.CommandCenterTransport)return window.CommandCenterTransport.request(path,body,key);
 const controller=new AbortController(), timer=setTimeout(()=>controller.abort(),12000);
 try {const response=await fetch(path,{method:body===undefined?'GET':'POST',headers:body===undefined?{}:{'Content-Type':'application/json','X-CC-Token':state.csrfToken,...(key?{'Idempotency-Key':key}:{})},body:body===undefined?undefined:JSON.stringify(body),signal:controller.signal});const result=await response.json();if(!response.ok)throw new Error(result.error||'Действие не удалось');return result;}
 catch(error){if(error.name==='AbortError')throw new Error('Сохранение не подтверждено. Повторите действие в этой форме: ключ операции сохранён.');throw error;}finally{clearTimeout(timer);}
}
async function load(){state=await api('/api/state');await refreshOperations();renderShell();render();}
function renderShell(){
 document.getElementById('nav').innerHTML=navItems.map(([key,name,img])=>`<a class="nav-link ${key===view?'active':''}" href="#${key}"${key===view?' aria-current="page"':''}>${icon(img)}<span>${name}</span></a>`).join('');
 const selector=document.getElementById('department');selector.innerHTML='<option value="all">Все отделы управления</option>'+state.departments.map(d=>`<option value="${e(d.id)}">${e(d.short)}</option>`).join('');selector.value=department;
 document.getElementById('scope-label').textContent=department==='all'?'Все отделы':deptName(department);
 const banner=document.getElementById('mode-banner');banner.className='mode-banner'+(state.mode==='local'?' local':'');
 banner.innerHTML=state.mode==='demo'?'<span><strong>Демонстрационный режим.</strong> Все сотрудники и рабочие показатели вымышлены. Банковские системы не подключены.</span><button data-mode="local">Мой пилот</button>':'<span><strong>Локальный пилот.</strong> Введите или импортируйте обезличенные записи. Живые подключения ещё не настроены.</span><button data-mode="demo">Открыть демо</button>';
 if(state.hostingMode==='github-pages')banner.innerHTML=`<span><strong>GitHub Pages · ${state.mode==='demo'?'демо':'пилот в браузере'}.</strong> Только тестовые данные. Записи сохраняются в этом браузере; общего сервера и автоматической рассылки нет.</span><button data-mode="${state.mode==='demo'?'local':'demo'}">${state.mode==='demo'?'Мой пилот':'Открыть демо'}</button>`;
}
function head(title,subtitle='',actions=''){return `<div class="page-head"><div><div class="eyebrow">${e(department==='all'?'Всё управление':deptName(department))}</div><h1>${e(title)}</h1><p class="subtitle">${e(subtitle)}</p></div><div class="actions">${actions}</div></div>`;}
function empty(title='Здесь пока нет записей',detail='Добавьте данные пилота или загрузите обезличенный файл в разделе «Источники и импорт».'){return `<div class="empty"><strong>${e(title)}</strong>${e(detail)}</div>`;}
function table(headers,body){return `<div class="panel table-wrap"><table><thead><tr>${headers.map(x=>`<th>${e(x)}</th>`).join('')}</tr></thead><tbody>${body}</tbody></table></div>`;}
function button(text,action,extra='',cls=''){return `<button type="button" class="${cls}" data-action="${action}" ${extra}>${e(text)}</button>`;}
function attention(){
 const cases=[];
 for(const x of rows('expiries')){if(x.expiryState==='known'&&daysUntil(x.expiresOn)<=14){const days=daysUntil(x.expiresOn);cases.push({title:days<0?`${x.resource}: срок истёк`:`${x.resource}: осталось ${days} дн.`,detail:`${personName(x.personId)} · ${dateText(x.expiresOn)}`,view:'expiries',red:days<=3});}else if(x.expiryState==='unknown'){cases.push({title:`Уточнить срок: ${x.resource}`,detail:personName(x.personId)+' · дата не подтверждена',view:'expiries'});}}
 for(const x of rows('requests').filter(x=>x.status==='pending'))cases.push({title:x.title,detail:`${personName(x.personId)} · ${x.target} · заявка ${x.externalId||'без номера'}`,view:'access'});
 for(const x of rows('risks').filter(x=>x.status==='open'))cases.push({title:x.title,detail:`${personName(x.personId)} · решение до ${dateText(x.dueOn)}`,view:'risks',red:x.severity==='high'});
 const ruler=state.operations.report.rows.filter(x=>department==='all'||x.departmentId===department), gaps=ruler.filter(x=>x.status==='attention'), unknown=ruler.filter(x=>x.status==='unknown'); if(gaps.length)cases.push({title:'Списания Project Ruler требуют проверки',detail:'Сотрудников: '+gaps.length+' · формат 8h, норма 40h/нед',view:'time',red:true}); if(unknown.length)cases.push({title:'Не хватает данных для проверки списаний',detail:'Сотрудников: '+unknown.length+' · автоматические письма для них заблокированы',view:'time'});
 return cases;
}
function overview(){
 const cases=attention(), people=rows('people'), requests=rows('requests'), known=rows('expiries').filter(x=>x.expiryState==='known'&&daysUntil(x.expiresOn)<=14);
 const stats=[['Сотрудников в реестре',people.length,'Записи текущего режима','people'],['Требует внимания',cases.length,'По срокам, заявкам и рискам','today'],['Заявки на доступ',requests.length,`${requests.filter(x=>x.status==='draft').length} локальных черновиков`,'access'],['Сроки до 14 дней',known.length,'Только известные даты','expiries']];
 return head('Сегодня',`${dateText(state.today)} · решения и следующий шаг`,button('Новая заявка','new','data-kind="requests"','primary'))+
 `<div class="stats">${stats.map(([name,num,note])=>`<div class="stat"><div class="stat-top">${name}</div><div class="stat-value">${num}</div><div class="stat-note">${note}</div></div>`).join('')}</div>`+
 `<div class="two-col"><div><section class="panel"><div class="panel-head"><h2>В фокусе</h2>${tag(cases.length+' ситуаций','blue')}</div>${cases.length?cases.map(x=>`<div class="case"><div class="case-marker ${x.red?'red':''}">!</div><div class="case-text"><strong>${e(x.title)}</strong><small>${e(x.detail)}</small></div>${button('Открыть','navigate',`data-view="${x.view}"`)}</div>`).join(''):empty('Ситуаций пока нет',people.length?'По введённым данным нет активных случаев. Полнота банковских данных пока не подтверждена.':'Добавьте сотрудников и рабочие записи для своего пилота.')}</section></div>
 <div><section class="panel"><div class="panel-head"><h2>Сводка по отделам</h2></div><div class="panel-body">${state.departments.map(d=>`<div class="metric-row"><span>${e(d.short)}</span><strong>${state.data.people.filter(x=>x.departmentId===d.id).length||'—'}</strong></div>`).join('')}<p class="subtle">Число записей, а не фактическая численность управления.</p></div></section><section class="panel"><div class="panel-head"><h2>Источники</h2></div><div class="panel-body">${state.integrations.map(x=>`<div class="metric-row"><span>${e(x.name)}</span>${tag(x.status==='links'?'Каталог ссылок':'Не подключён')}</div>`).join('')}<p class="subtle">Сейчас данные обновляются при ручном вводе и импорте.</p>${button('Настроить данные пилота','navigate','data-view="integrations"')}</div></section></div></div>`;
}
function peopleView(){const data=rows('people');return head('Команда','Рабочие карточки и области ответственности',button('Добавить сотрудника','new','data-kind="people"','primary'))+(data.length?table(['Сотрудник','Отдел','Проект','Компетенции','Доступность'],data.map(p=>`<tr><td><div class="person"><span class="avatar">${e(p.name.split(' ').map(x=>x[0]).slice(0,2).join(''))}</span><div><span class="name">${e(p.name)}</span><div class="subtle">${e(p.role)}</div></div></div>${source(p)}</td><td>${e(deptName(p.departmentId))}</td><td>${e(p.project||'Не указан')}</td><td>${e((p.skills||[]).join(', ')||'Не подтверждены')}</td><td>${tag(p.availability==='available'?'Доступен':p.availability==='absent'?'Отсутствует':'Неизвестно',p.availability==='available'?'green':'')}</td></tr>`).join('')):empty());}
const requestStatus={draft:['Черновик','blue'],recorded:['Номер записан','blue'],pending:['Ожидает решения','amber'],closed:['Закрыта в источнике',''],unknown:['Статус неизвестен','']};
function accessView(){const data=rows('requests');return head('Доступы','Комплект → черновик → штатная заявка → подтверждение выдачи',button('Новый черновик','new','data-kind="requests"','primary'))+`<div class="notice">Пакеты — примеры для пилота. Сохранение черновика не отправляет заявку и не выдаёт доступ. Закрытая заявка не подтверждает фактическую выдачу.</div>`+(data.length?table(['Заявка','Сотрудник','Система / номер','Состояние','Действие'],data.map(x=>`<tr><td><span class="name">${e(x.title)}</span><div class="subtle">${e((x.resources||[]).join(' · '))}</div>${source(x)}</td><td>${e(personName(x.personId))}</td><td>${e(x.target)}<br>${e(x.externalId||'Номер не записан')}</td><td>${tag(...requestStatus[x.status])}</td><td><div class="actions">${button('Текст заявки','request-text',`data-id="${e(x.id)}"`)}${editable(x)&&['draft','recorded'].includes(x.status)?button('Записать номер','record-request',`data-id="${e(x.id)}"`):''}</div></td></tr>`).join('')):empty());}
function expiryLabel(x){if(x.expiryState==='unknown')return tag('Дата неизвестна');if(x.expiryState==='never')return tag('Без срока — по источнику');const d=daysUntil(x.expiresOn);return tag(d<0?`Истёк ${-d} дн. назад`:d===0?'Истекает сегодня':`Осталось ${d} дн.`,d<=3?'red':d<=14?'amber':'');}
function expiriesView(){const data=rows('expiries');return head('Сроки действия','Доступы, учётные записи и сертификаты — только метаданные',button('Добавить срок','new','data-kind="expiries"','primary'))+(data.length?table(['Ресурс','Владелец','Тип','Дата','Состояние'],data.map(x=>`<tr><td><span class="name">${e(x.resource)}</span>${source(x)}</td><td>${e(personName(x.personId))}</td><td>${e({access:'Доступ',account:'Учётная запись',certificate:'Сертификат'}[x.kind])}</td><td>${x.expiryState==='known'?e(dateText(x.expiresOn)):'—'}</td><td>${expiryLabel(x)}</td></tr>`).join('')):empty());}
function timeView(){const data=rows('time'), total=data.reduce((n,x)=>n+x.hours,0);return head('Учёт времени','Черновик помогает заполнить табель; фактические часы подтверждает сотрудник',button('Добавить запись','new','data-kind="time"','primary'))+`<div class="notice">Всего в выбранных записях: <strong>${e(total.toLocaleString('ru-RU'))} ч.</strong> Подтверждение здесь локальное. Передача в банковскую систему табеля ещё не подключена.</div>`+(data.length?table(['Сотрудник / дата','Проект','Часы','Состояние','Действие'],data.map(x=>`<tr><td><span class="name">${e(personName(x.personId))}</span><div class="subtle">${e(dateText(x.date))}</div>${source(x)}</td><td>${e(x.project)}<div class="subtle">${e(x.note||'')}</div></td><td><strong>${e(x.hours)} ч.</strong></td><td>${tag(x.status==='draft'?'Черновик':x.status==='confirmed_source'?'Подтверждено в источнике':'Подтверждено локально',x.status==='draft'?'amber':'blue')}</td><td><div class="actions">${x.status==='draft'&&editable(x)?button('Подтвердить','confirm-time',`data-id="${e(x.id)}"`):''}${button('Повторить как черновик','repeat-time',`data-id="${e(x.id)}"`)}</div></td></tr>`).join('')):empty());}
function releasesView(){const data=rows('releases');return head('Релизы','Факты тестирования и доказательства готовности')+`<div class="notice">Результаты тестов сами по себе не являются допуском релиза. Регламент готовности и владелец решения ещё не подключены.</div>`+(data.length?`<div class="card-grid">${data.map(x=>{const total=x.passed+x.failed+x.blocked+x.notStarted;return `<section class="card"><h2>${e(x.title)}</h2>${source(x)}<p><strong>${total}</strong> сценариев в данном срезе</p><div class="metric-row"><span>Пройдено</span>${tag(x.passed+'','green')}</div><div class="metric-row"><span>Ошибка</span>${tag(x.failed+'','red')}</div><div class="metric-row"><span>Заблокировано</span>${tag(x.blocked+'','amber')}</div><div class="metric-row"><span>Не начато</span><strong>${x.notStarted}</strong></div><p>Готовность: не оценена по банковскому регламенту.</p></section>`;}).join('')}</div>`:empty('Источник релизов пока не подключён','Можно импортировать обезличенный срез тестов. Живые TestIT / Allure / GitLab требуют проверки.'));}
function risksView(){const data=rows('risks');return head('Риски и блокеры','Владелец, срок решения и текущее состояние',button('Добавить риск','new','data-kind="risks"','primary'))+(data.length?table(['Риск','Владелец','Приоритет','Решить до','Состояние'],data.map(x=>`<tr><td><span class="name">${e(x.title)}</span>${source(x)}</td><td>${e(personName(x.personId))}</td><td>${tag({high:'Высокий',medium:'Средний',low:'Низкий'}[x.severity],x.severity==='high'?'red':x.severity==='medium'?'amber':'')}</td><td>${e(dateText(x.dueOn))}</td><td>${tag(x.status==='open'?'Открыт':'Закрыт',x.status==='open'?'amber':'')}${x.status==='open'&&editable(x)?`<div class="actions">${button('Закрыть','close-risk',`data-id="${e(x.id)}"`)}</div>`:''}</td></tr>`).join('')):empty());}
function servicesView(){const data=rows('services');return head('Данные и стенды','Pipeline, качество и свежесть данных, состояние окружений')+`<div class="notice">Пройденный pipeline не доказывает качество или свежесть данных. Текущее состояние здесь — введённый или импортированный срез.</div>`+(data.length?table(['Объект','Тип','Состояние','Последнее наблюдение'],data.map(x=>`<tr><td><span class="name">${e(x.title)}</span>${source(x)}</td><td>${x.type==='pipeline'?'Pipeline':'Тестовый стенд'}</td><td>${tag({healthy:'По срезу доступен',degraded:'Есть ограничения',down:'По срезу недоступен',unknown:'Неизвестно'}[x.status],x.status==='down'?'red':x.status==='degraded'?'amber':x.status==='healthy'?'green':'')}</td><td>${e(dateText(x.lastObservedAt))}</td></tr>`).join('')):empty('Мониторинг пока не подключён','План интеграций: состояние задач, задержка, freshness, качество, изменения схем и зависимости.'))+`<div class="card-grid"><section class="card"><h3>Обработка и хранение</h3><p>Запуски pipeline, задержки загрузки, freshness и проверки качества.</p></section><section class="card"><h3>Технологии больших данных</h3><p>Платформенные сервисы, ёмкость, обновления и общие зависимости.</p></section><section class="card"><h3>Маркетинговые системы</h3><p>Связь изменений, данных, интеграционных проверок и релизов.</p></section></div>`;}
function knowledgeView(){const data=rows('documents');return head('Знания','Поиск по введённым документам; внутренний RAG — следующий этап',`<input class="search" id="doc-search" placeholder="Найти инструкцию" aria-label="Найти инструкцию">`)+`<div id="doc-results">${knowledgeResults(data)}</div>`;}
function knowledgeResults(data){return data.length?data.map(x=>`<section class="panel"><div class="panel-head"><h2>${e(x.title)}</h2></div><div class="panel-body"><div class="doc-text">${e(x.text)}</div>${source(x)}</div></section>`).join(''):empty('Документы не найдены','Загрузите обезличенные инструкции через импорт. Поиск работает по тексту без внешней модели.');}
function briefText(){const cases=attention();return `Статус на ${dateText(state.today)}. Область: ${department==='all'?'управление':deptName(department)}.\nРежим: ${state.mode==='demo'?'демонстрационные данные':'локальные записи и ручной импорт'}. Банковские источники не подключены.\n\nВнимание: ${cases.length} ситуаций.\n${cases.map((x,i)=>`${i+1}. ${x.title}. ${x.detail}`).join('\n')||'Активных случаев в введённых данных нет. Полнота данных управления не подтверждена.'}\n\nЛокальных черновиков заявок: ${rows('requests').filter(x=>x.status==='draft').length}.\nПроверка списаний: ${state.operations.report.rows.filter(x=>(department==='all'||x.departmentId===department)&&x.status==='attention').length} сотрудников с отклонениями.\n\nСводка сформирована по правилам из текущих записей. Внутренняя LLM пока не подключена.`;}
function briefView(){return head('Сводка управления','Готовый текст по текущим записям и выбранному отделу',button('Скопировать сводку','copy-brief','','primary'))+`<section class="panel"><div class="panel-head"><h2>Что требует внимания</h2>${tag('По правилам','blue')}</div><div class="panel-body"><div class="summary">${e(briefText())}</div></div></section><div class="notice">AI-сводки, ревью требований и сценариев, поиск с источниками и анализ влияния предусмотрены в исследовании. Этот экран не имитирует подключённую модель.</div>`;}
function integrationsView(){return head('Источники и импорт','Рабочие данные MVP и состояние будущих подключений',`<a href="/api/export" class="export-link">Экспорт JSON</a>${button('Импорт JSON','import','','primary')}`)+`<div class="card-grid">${state.integrations.map(x=>`<section class="card"><h2>${e(x.name)}</h2><p>${e(x.detail)}</p>${tag(x.status==='links'?'Каталог ссылок':'Не подключён')}</section>`).join('')}</div><div class="panel"><div class="panel-head"><h2>Данные пилота</h2></div><div class="panel-body"><p class="subtle">Обезличенный JSON загружается в «Мой пилот», синтетический — в демо. Импорт проверяет структуру и связи, объединяет записи по ID и не удаляет отсутствующие строки. До 512 КБ за один импорт.</p><div class="actions"><a href="/api/template">Скачать пустой шаблон</a>${button('Добавить сотрудника','new','data-kind="people"')}</div><p class="subtle">Формат и пример лежат в папке проекта: app/fixtures. Пароли, токены и ключи не являются полями контракта.</p></div></div><div class="panel"><div class="panel-head"><h2>Журнал локальных действий</h2>${tag(state.audit.length+' записей')}</div>${state.audit.length?table(['Когда','Действие','Запись'],state.audit.map(x=>`<tr><td>${e(x.at)}</td><td>${e(x.action)}</td><td>${e(x.objectId)}</td></tr>`).join('')):empty('Действий ещё нет','Сохранения и импорт появятся здесь.')}</div>`;}
function researchView(){return head('Исследование','Архитектура, автоматизация и реализация для пяти отделов')+`<div class="card-grid">${[['report','Выводы для управления','Общая концепция, пять отделов, MVP и масштабирование'],['realtime-integrations','Данные в реальном времени','ИнфраМенеджер, ТЕЗИС, источники, задержки и ограничения'],['operating-model','Процессы и платформы','Каталог автоматизации и сравнение вариантов'],['ai-identity','Внутренний AI и доступы','RAG, Qwen, жизненный цикл и ротация']].map(([id,title,text])=>`<section class="card"><h2>${title}</h2><p>${text}</p>${button('Читать','research',`data-doc="${id}"`)}</section>`).join('')}</div>`;}
function render(){const renderers={today:overview,people:peopleView,access:accessView,expiries:expiriesView,time:rulerView,grafana:grafanaView,releases:releasesView,risks:risksView,services:servicesView,knowledge:knowledgeView,brief:briefView,integrations:integrationsView,research:researchView};main.innerHTML=(renderers[view]||overview)();if(state.hostingMode==='github-pages'&&view==='integrations'){main.querySelector('.panel-body p').textContent='Публичная демонстрация: импортируются только синтетические тестовые данные. Данные пилота и демо хранятся отдельно в этом браузере и не отправляются на GitHub. Очистка данных браузера удалит записи: сохраните экспорт. Для рабочих данных нужен внутренний сервер с авторизацией.';}}
function navigate(next){if(!navItems.some(x=>x[0]===next))next='today';view=next;if(location.hash!=='#'+next)location.hash=next;renderShell();render();}
function openDialog(title,body){document.getElementById('modal-content').innerHTML=`<div class="dialog-head"><h2 id="dialog-title">${e(title)}</h2><button data-action="close-dialog" aria-label="Закрыть">×</button></div><div class="dialog-body">${body}</div>`;if(!modal.open)modal.showModal();}
function field(label,name,input,full=false){return `<label class="field ${full?'full':''}">${e(label)}${input}</label>`;}
function input(name,type='text',value='',extra=''){return `<input name="${name}" type="${type}" value="${e(value)}" ${extra}>`;}
function select(name,options,value){return `<select name="${name}">${options.map(([id,title])=>`<option value="${e(id)}"${id===value?' selected':''}>${e(title)}</option>`).join('')}</select>`;}
function newForm(kind,prefill={}){
 const people=rows('people'), selected=prefill.personId||people[0]?.id;
 if(kind!=='people'&&!people.length){openDialog('Сначала добавьте сотрудника',`<p>Для записи нужен сотрудник выбранного отдела.</p>${button('Добавить сотрудника','new','data-kind="people"','primary')}`);return;}
 const personField=field('Сотрудник','personId',select('personId',people.map(x=>[x.id,x.name]),selected),true);
 let fields='', title='';
 if(kind==='people'){
  title='Добавить сотрудника';fields=field('Имя или обезличенный псевдоним','name',input('name','text','', 'required maxlength="120"'),true)+field('Отдел','departmentId',select('departmentId',state.departments.map(x=>[x.id,x.short]),department==='all'?'qa':department),true)+field('Роль','role',input('role','text','QA инженер','required maxlength="120"'))+field('Проект','project',input('project','text','','maxlength="160"'))+field('Компетенции через запятую','skills',input('skills','text','','maxlength="500"'),true)+field('Доступность','availability',select('availability',[['unknown','Не подтверждена'],['available','Доступен'],['absent','Отсутствует']],'unknown'),true);
 }else if(kind==='requests'){
  title='Черновик заявки на доступ';fields=personField+field('Пример комплекта','packageId',select('packageId',state.packages.map(x=>[x.id,x.name]),state.packages[0].id),true)+`<div class="field full"><small id="package-resources">${e(state.packages[0].resources.join(' · '))}</small></div>`+field('Штатная система оформления','target',select('target',[['ИнфраМенеджер','ИнфраМенеджер'],['ТЕЗИС','ТЕЗИС']],'ИнфраМенеджер'),true)+field('Обоснование / задача','reason','<textarea name="reason" required maxlength="1000" placeholder="Для какой работы нужен доступ"></textarea>',true);
 }else if(kind==='expiries'){
  title='Добавить срок действия';fields=personField+field('Название ресурса','resource',input('resource','text','','required maxlength="160"'),true)+field('Тип','kind',select('kind',[['access','Доступ'],['account','Учётная запись'],['certificate','Сертификат']],'access'))+field('Состояние даты','expiryState',select('expiryState',[['known','Дата известна'],['unknown','Дата неизвестна'],['never','Без срока — подтверждено']],'known'))+field('Истекает','expiresOn',input('expiresOn','date',state.today,'required'),true)+`<div class="field full"><small>Указывайте метаданные. Пароли и содержимое сертификата не нужны.</small></div>`;
 }else if(kind==='time'){
  title='Черновик времени';fields=personField+field('Дата','date',input('date','date',state.today,'required'))+field('Фактические часы','hours',input('hours','number',prefill.hours??'', 'required min="0.01" max="24" step="0.01"'))+field('Проект / задача','project',input('project','text',prefill.project||person(selected)?.project||'','required maxlength="160"'),true)+field('Комментарий','note',`<textarea name="note" maxlength="1000">${e(prefill.note||'')}</textarea>`,true)+(prefill.id?`<div class="field full"><small>Повтор записи за ${e(dateText(prefill.date))}. Проверьте дату, проект и реальные часы.</small></div>`:'');
 }else if(kind==='risks'){
  title='Добавить риск';fields=personField+field('Риск / необходимое решение','title',input('title','text','','required maxlength="240"'),true)+field('Приоритет','severity',select('severity',[['high','Высокий'],['medium','Средний'],['low','Низкий']],'medium'))+field('Решить до','dueOn',input('dueOn','date',state.today,'required'));
 }
 const key=crypto.randomUUID();
 openDialog(title,`<form id="create-form" data-kind="${kind}" data-key="${key}"><div class="form-grid">${fields}</div><div class="form-error" role="alert"></div><div class="form-footer">${button('Отмена','close-dialog')}<button class="primary" type="submit">Сохранить ${kind==='requests'||kind==='time'?'черновик':'запись'}</button></div></form>`);
}
function requestText(x){const ending=x.status==='draft'&&editable(x)?'Черновик сохранён локально; заявка не отправлялась из Command Center.':`Состояние: ${requestStatus[x.status][0]}. Внешний номер: ${x.externalId||'не записан'}. Это сохранённая информация; фактическая выдача доступа не проверена.`;return `Заявка — ${x.target}\nСотрудник: ${personName(x.personId)}\nОтдел: ${deptName(x.departmentId)}\nНазвание: ${x.title}\nРесурсы: ${(x.resources||[]).join(', ')}\nОбоснование: ${x.reason||'Уточнить'}\n\nПроверьте перечень ресурсов, роль, область и срок доступа по штатному каталогу. Пакеты MVP являются примерами.\nЗапись ${x.id}. ${ending}`;}
async function copyText(text){try{await navigator.clipboard.writeText(text);toast('Текст скопирован');}catch{openDialog('Текст для копирования',`<label class="field">Выделите и скопируйте<textarea readonly rows="12">${e(text)}</textarea></label>`);}}
document.addEventListener('click',async event=>{
 const modeButton=event.target.closest('[data-mode]');if(modeButton){try{await api('/api/mode',{mode:modeButton.dataset.mode});await load();toast(state.mode==='local'?'Открыт ваш локальный пилот':'Открыт демонстрационный режим');}catch(error){toast(error.message);}return;}
 const b=event.target.closest('[data-action]');if(!b)return;const {action,id,kind}=b.dataset;
 try{
  if(action==='navigate')navigate(b.dataset.view);
  else if(action==='close-dialog')modal.close();
  else if(action==='new')newForm(kind);
  else if(action==='request-text'){const x=state.data.requests.find(x=>x.id===id);openDialog('Текст заявки',`<label class="field">Подготовлено для оформления в штатной системе<textarea id="request-copy" readonly rows="12">${e(requestText(x))}</textarea></label><div class="form-footer">${button('Скопировать','copy-request','','primary')}</div>`);}
  else if(action==='copy-request')await copyText(document.getElementById('request-copy').value);
  else if(action==='record-request')openDialog('Записать номер штатной заявки',`<form id="record-form" data-id="${e(id)}">${field('Внешний номер','externalId',input('externalId','text','','required maxlength="160"'),true)}<p class="subtle">Вы подтверждаете, что оформили заявку в штатной системе. Её статус и выдача доступа этим действием не проверяются.</p><div class="form-error" role="alert"></div><div class="form-footer"><button class="primary" type="submit">Сохранить номер</button></div></form>`);
  else if(action==='confirm-time'){b.disabled=true;await api('/api/action/time/'+encodeURIComponent(id),{action:'confirm'});await load();toast('Время подтверждено локально. Внешний табель не изменялся.');}
  else if(action==='repeat-time')newForm('time',state.data.time.find(x=>x.id===id));
  else if(action==='close-risk'){b.disabled=true;await api('/api/action/risks/'+encodeURIComponent(id),{action:'close'});await load();toast('Локальный риск закрыт');}
  else if(action==='copy-brief')await copyText(briefText());
  else if(action==='import')openDialog(state.hostingMode==='github-pages'?'Импорт тестовых записей':'Импорт обезличенных записей',`<form id="import-form"><label class="field">Файл JSON<input name="file" type="file" accept="application/json,.json" required></label><p class="subtle">До 512 КБ. Импорт объединяет записи по ID и проверяет связи. ${state.hostingMode==='github-pages'?'Только datasetType=synthetic. Шаблон можно скачать в разделе «Источники и импорт». Импорт сохраняется в текущий режим этого браузера.':'Используйте формат app/fixtures в папке проекта.'}</p><div class="form-error" role="alert"></div><div class="form-footer"><button class="primary" type="submit">Проверить и импортировать</button></div></form>`);
  else if(action==='research'){b.disabled=true;const result=await api('/api/research/'+b.dataset.doc);openDialog(b.closest('.card').querySelector('h2').textContent,`<pre class="research-text">${e(result.text)}</pre>`);}
 }catch(error){toast(error.message);}finally{b.disabled=false;}
});
document.addEventListener('change',event=>{
 if(event.target.id==='department'){department=event.target.value;renderShell();render();}
 if(event.target.name==='packageId'){const selected=state.packages.find(x=>x.id===event.target.value);document.getElementById('package-resources').textContent=selected.resources.join(' · ');}
 if(event.target.name==='expiryState'){const f=event.target.form.elements.expiresOn;f.disabled=event.target.value!=='known';f.required=event.target.value==='known';}
});
document.addEventListener('input',event=>{if(event.target.id==='doc-search'){const q=event.target.value.toLocaleLowerCase('ru-RU');document.getElementById('doc-results').innerHTML=knowledgeResults(rows('documents').filter(x=>(x.title+' '+x.text).toLocaleLowerCase('ru-RU').includes(q)));}});
document.addEventListener('submit',async event=>{
 const form=event.target;if(!['create-form','record-form','import-form'].includes(form.id))return;event.preventDefault();const submit=form.querySelector('[type="submit"]');submit.disabled=true;form.querySelector('.form-error').textContent='';
 try{
  const values=Object.fromEntries(new FormData(form).entries());
  if(form.id==='create-form'){
   const kind=form.dataset.kind;let payload;
   if(kind==='people')payload={...values,skills:values.skills.split(',').map(x=>x.trim()).filter(Boolean)};
   else {const selected=person(values.personId);payload={...values,departmentId:selected.departmentId};
    if(kind==='requests'){const p=state.packages.find(x=>x.id===values.packageId);payload.title=p.name;payload.resources=p.resources;}
    if(kind==='expiries'){payload.expiresOn=values.expiryState==='known'?values.expiresOn:null;}
    if(kind==='time')payload.hours=Number(values.hours);
   }
   await api('/api/create/'+kind,payload,form.dataset.key);
  }else if(form.id==='record-form')await api('/api/action/requests/'+encodeURIComponent(form.dataset.id),{action:'record',externalId:values.externalId});
  else {const file=values.file;if(file.size>524288)throw new Error('Файл больше 512 КБ');let parsed;try{parsed=JSON.parse(await file.text());}catch{throw new Error('Не удалось прочитать JSON');}const result=await api('/api/import',parsed);toast(`Импортировано ${result.imported} записей`);}
  modal.close();try{await load();if(form.id!=='import-form')toast('Сохранено в текущем режиме');}catch{toast('Сохранено. Перечитать записи не удалось; нажмите «Обновить». Повторно сохранять не нужно.');}
 }catch(error){form.querySelector('.form-error').textContent=error.message;}finally{submit.disabled=false;}
});
document.getElementById('refresh').addEventListener('click',async()=>{try{await load();toast('Локальные записи обновлены');}catch(error){toast(error.message);}});
window.addEventListener('hashchange',()=>{if(state)navigate(location.hash.slice(1));});
view=navItems.some(x=>x[0]===location.hash.slice(1))?location.hash.slice(1):'today';
load().then(()=>{
 if(document.modelContext?.registerTool){const context=document.modelContext;try{Promise.resolve(context.registerTool({name:'command_center_read_view',title:'Прочитать текущий экран',description:'Возвращает текущие локальные записи выбранного отдела. Демо и импорт не являются подключёнными банковскими данными.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute(input){if(!input||typeof input!=='object'||Object.keys(input).length)throw new Error('Параметры не принимаются');return {mode:state.mode,department,view,data:Object.fromEntries(Object.keys(state.data).map(k=>[k,rows(k)])),operations:{ruler:{...rulerReport(),rows:rulerRows()},dashboards:state.operations.dashboards.filter(x=>department==='all'||x.departmentId==='all'||x.departmentId===department),outbox:state.operations.outbox.filter(x=>department==='all'||x.departmentId===department)}};}})).catch(()=>{});}catch{}}
}).catch(error=>{main.innerHTML=`<div class="empty"><strong>Не удалось открыть записи</strong>${e(error.message)}<p>${window.CommandCenterTransport?'Обновите страницу и разрешите хранение данных сайта в браузере.':'Проверьте, что локальный сервер проекта запущен, и обновите страницу.'}</p></div>`;});
setInterval(async()=>{if(!state||modal.open||document.hidden||['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName))return;try{await load();}catch{document.getElementById('mode-banner').textContent='Локальные записи временно недоступны. Показан предыдущий срез; нажмите «Обновить». Банковские источники не подключены.';}},30000);
